### PR TITLE
Refactor and resize view port. Resize view port does not scale the ga…

### PR DESCRIPTION
**Pull request by coppermouse**
…me, it changes the field of view. Camera logic is more center-based

### CODE REVIEW

**Comment by hasnain-495** [comment]
there's a problem with this
when you the start it, the view_port_y is at the bottom, but when you resize the screen, it centers then
and the scaling is a bit much, like instead of 2x, can you for like 1.7x - 1.8x

and... the smooth scrolling is gone too, but it's okay, don't think it's really needed, i guess

and besides these, everything else is okay!!

**Comment by coppermouse** [comment]
Yes, I can fix the smooth scrolling and let us say we do scale 1.7 for now on. The scale can be in a config later.

**Comment by hasnain-495** [comment]
yea, about the scaling, when i added the rendered map, it seems like we'll be needing exact 2x scale instead of something below it and yes, it'll be better to have it in the config.
also the player-sprite will be drawn in the tiled class now, cuz layerings and all...

P.S: i didn't meant to close this commit, i accidently clicked there... but it seems like i can re-open it

**Comment by coppermouse** [comment]
1. fixed conflict and render scroll tiles works with new camera logic.
2. smooth camera (is easy to adjust now, feel free to adjust it) hopefully it can produce the same smooth camera.

So player has to be drawn in tiled class now? That might be hard to resolve with my new code, perhaps we have to skip my changes, not sure.

Also not sure about " the view_port_y is at the bottom" thing.

Feel free to merge :)

**Comment by coppermouse** [comment]
Now everything seems to be working. I do not see any issues.

If issues with scale just set scale to 1.

If you like the code/changes merge as soon as possible to prevent further issues/conflicts :)

**Comment by hasnain-495** [comment]
i'm merging this for now, but there still one issue with it, when you start it up, the tiles's and player's rect is horizontally squeezed a bit, but when you resize the screen a little, it becomes normal

**Comment by coppermouse** [comment]
sorry, I do not see the issue, perhaps I can share my desktop? It could also be good to talk about the project, what you want to do and what I can help with and so on.

**Pull request merged**
